global:
  username: nhtlong
  name: "color"
  save_dir: ./runs
  use_fp16: true
  debug: false
  verbose: true
  SEED: 1337
  pretrained: null
  resume: null
data:
  name: CropVehDataset
  args:
    CITYFLOW_PATH: "data/meta/extracted_frames"
    SIZE: 288
    CROP_AREA: 1.0 ## new_= CROP_AREA * old_w
    train:
      color_csv: "data/meta/srl/color/col_train.csv"
      vehtype_csv: "data/meta/srl/veh/train_fraction.csv"
      json_path: "data/meta/split/train.json"
      loader:
        batch_size: 32
        num_workers: 2
        shuffle: True
        drop_last: True
    val:
      color_csv: "data/meta/srl/color/col_train.csv"
      vehtype_csv: "data/meta/srl/veh/train_fraction.csv"
      json_path: "data/meta/split/val.json"
      loader:
        batch_size: 32
        num_workers: 2
        shuffle: False
        drop_last: False
extractors:
  img_encoder:
    name: EfficientNetExtractor
    args:
      version: 0
      from_pretrained: True
      freeze: True
model:
  name: VehColorClassifer
  args:
    NUM_CLASS: 8 # Num of unique colors
    EMBED_DIM: 768
metric:
  - name: F1score
    args:
      label_key: "color_lbls"
      num_classes: 8
trainer:
  lr: 0.001
  num_epochs: 10000
  clip_grad: 10.0
  evaluate_interval: 1
  print_interval: 20
  save_interval: 1000
callbacks:
  - name: ModelCheckpoint
    args:
      filename: "Color-{epoch}-{val/f1:.4f}"
      monitor: "val/f1"
      verbose: True
      save_top_k: 3
      mode: max
  - name: EarlyStopping
    args:
      monitor: "val/f1"
      min_delta: 0.0001
      patience: 15
      verbose: False
      mode: max
  - name: VisualizerCallback
    args:
      motion_path: "data/meta/motion_map",
      gt_json_path: "data/meta/val.json",
      query_results_json: "temps/query_results.json",
      mapping_json: "temps/track_id_mapping.json"
  - name: LearningRateMonitor
    args:
      logging_interval: step