data:
  text:
    name: AIC22TextJsonDatasetSubject
    args:
      json_path: /content/AIC2022-VER/data/test_queries.json
      tok_model_name: bert-base-uncased
      num_texts_used: 5
      use_other_views: True
      shuffle: False
  track:
    name:  AIC22TrackJsonWithMotionDataset
    args:
      image_dir: /content/AIC2022-VER/data/extracted_frames
      json_path: /content/AIC2022-VER/data/test_tracks.json
      motion_path: /content/AIC2022-VER/data/motion_map
      meta_json: null
      crop_area: 1.0
      image_size: 288

extractors:
  img_encoder:
    name: EfficientNetExtractor
    args:
      version: 0
      from_pretrained: True
      freeze: True
  lang_encoder:
    name: LangExtractor
    args:
      pretrained: "bert-base-uncased"
      freeze: True
model:
  name: HCMUSSubject
  args:
    NUM_CLASS: 2155 # total tracks
    EMBED_DIM: 768
    car_idloss: True
    mo_idloss: True
    share_idloss: True
