global:
  debug: true
  save_dir: ./runs
  device: cuda:0
  use_fp16: true
  pretrained: null
data:
  CITYFLOW_PATH: "data/meta/extracted_frames"
  TRAIN_JSON_PATH: "data/meta/train.json"
  EVAL_JSON_PATH: "data/meta/val.json"
  SIZE: 288
  CROP_AREA: 1.0 ## new_= CROP_AREA * old_w
  TEST_TRACKS_JSON_PATH: "data/meta/test-tracks.json"
  USE_MOTION: True
  MOTION_PATH: "data/meta/motion_map"
model:
  name: base
  args:
    NAME: base
    BERT_TYPE: "BERT"
    BERT_NAME: "bert-base-uncased"
    IMG_ENCODER: se_resnext50_32x4d
    NUM_CLASS: 2498 # total tracks
    EMBED_DIM: 1024
    car_idloss: True
    mo_idloss: True
    share_idloss: True
trainer:
  num_epochs: 10000
  clip_grad: 10.0
  evaluate_interval: 1
  print_interval: 20
  save_interval: 1000
